### ISSUE TITLE
Visual Explorer doesn't give any scope/components/concerns due to MismatchedInputException

### ISSUE THREAD

**Issue by ringods** [zeljkoobrenovic/sokrates#13]
I launched the Sokrates Visual Explorer, selected the source root folder, picked my required set of file extensions and let it generate a `_sokrates/config.json` file. But after that, nothing more happens. When looking at the console where I started the Visual Explorer, I see this repetitively:

```
Aug 06, 2020 12:19:14 PM nl.obren.sokrates.common.io.JsonMapper getObject
SEVERE: 
JSON:

==================

Aug 06, 2020 12:19:14 PM nl.obren.sokrates.common.io.JsonMapper getObject
SEVERE: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
Aug 06, 2020 12:19:14 PM nl.obren.sokrates.codeexplorer.configuration.CodeConfigurationView getConfigurationFromEditor
SEVERE: java.lang.IllegalArgumentException: No content to map due to end-of-input (line 1, column 0)
```

Any idea on the cause of this?

Context:
* MacOS 10.15.6
* Amazon Corretto 11 (installed via Homebrew)
* JavaFX 11.0.2 SDK (downloaded from https://gluonhq.com/products/javafx/)

**Comment by zeljkoobrenovic** [comment]
Fixed with robust JSON parsing.
