### ISSUE TITLE
Default importPath for fileHistoryAnalysis is incorrect

### ISSUE THREAD

**Issue by jelmerk** [zeljkoobrenovic/sokrates#14]
The instructions for generating a report for junit at www.sokrates.dev are as followed

```
    git clone https://github.com/junit-team/junit4
    cd junit4
    git ls-files -z | xargs -0 -n1 -I{} -- git log --date=short --format="%ad %ae %H {}" {} > git-history.txt

    java -jar sokrates-0.9.jar init
    java -jar sokrates-0.9.jar generateReports

    open _sokrates/reports/html/index.html
```

The init step generates a config.json file that contains this snippet by default

```
  "fileHistoryAnalysis" : {
    "importPath" : "../git-history.txt",
    "ignoreContributors" : [ ]
  }
```

However the importPath will be resolved relative to the project root, so in the above example it would not find the file

**Comment by zeljkoobrenovic** [comment]
The input path is resolved relative to the configuration file, which is in _sokrates folder. hence ".." prefix.

**Comment by jelmerk** [comment]
I wanted to proof you wrong but it seems I had a git-history.txt in the folder below the checkout folder and that's why it failed for me.

This is not really sound logic though.

https://github.com/zeljkoobrenovic/sokrates/blob/e5528a77238bfd99568f16a0cdfea2f1084fe56f/codeanalyzer/src/main/java/nl/obren/sokrates/sourcecode/analysis/FileHistoryAnalysisConfig.java#L37

Why not check for sokratesConfigFolder.isAbsolute() instead of if (new File(importPath).exists())
