### ISSUE TITLE
DuplicationEngineTest fails when run together with the other tests, but not in isolation

### ISSUE THREAD

**Issue by markhm** [zeljkoobrenovic/sokrates#7]
Interesting problem here. Perhaps you have an idea what this could be based on the test result. 

On macOS (details below), one of the tests fails when run together with the other tests [1], but not when run in isolation [2]. 

[1] **Running all tests together**
```
cd codeanalyzer
mvn test
```

Result:
```
...
Failed tests:
  DuplicationEngineTest.findDuplicates:69 expected:<9> but was:<1>
Tests run: 252, Failures: 1, Errors: 0, Skipped: 0
...
```

[2] **Running the failing test in isolation**
```
cd codeanalyzer
mvn -Dtest=nl.obren.sokrates.sourcecode.duplication.DuplicationEngineTest test
```
Result:
```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.103 sec
Results :
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```
----
I have reproduced this on/with:
macOS Catalina 10.15.1 and maven-3.6.2 using
- openjdk version "13" 2019-09-17, OpenJDK Runtime Environment (build 13+33), OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing) and
- java version "1.8.0_221", Java(TM) SE Runtime Environment (build 1.8.0_221-b11), Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode).

**Comment by zeljkoobrenovic** [comment]
It should work now. Sorting of results (or lack of it) was an issue.
