### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by robinvanb** [zeljkoobrenovic/sokrates#9]
I wanted to try out sokrates on our projects but it keeps crashing with an OutOfMemoryError.
I'm running the command: java -jar -Xmx8g -Xms8g sokrates-0.9.jar generateReports but even then it runs out of heap space.
The project has around 79,000 lines.

**Comment by zeljkoobrenovic** [comment]
Thanks for the feedback. This is strange, as I run projects above 1 MLOC with the same setting memory settings. Is it an open-source project so I can take a look? Has some library folder accidentally been included in scope?

**Comment by robinvanb** [comment]
Unfortunately it's not an open source project.
It's a gradle multi-module project, I've used the `init` command I don't see any specific excludes. Any pointers?

**Comment by zeljkoobrenovic** [comment]
Try editing _sokrates/config.json and skip duplication and dependency analysis (set skip to true):
`  "analysis" : {
    "skipDuplication" : true,
    "skipDependencies" : true,
    "cacheSourceFiles" : true,
    "saveDailyHistory" : false,
    "analyzerOverrides" : [ ]
  }
`

Then try to generate reports and open Overview.html to see how many files and lines have been included.

**Comment by robinvanb** [comment]
I did that and it takes an insane amount of time, but looking at the output:
```
Loading lib.es2018.full.d.ts
Loading tsserverlibrary.js
Loading cancellationToken.js
Loading lib.es2015.reflect.d.ts
Loading lib.es2019.string.d.ts
Loading lib.es2016.d.ts
Loading lib.es2015.core.d.ts
Loading diagnosticMessages.generated.json
Loading lib.es2020.d.ts
Loading lib.es2020.full.d.ts
Loading typescript.js
```

We can see that it's looking at the node_modules folder. 
I checked where `typescript.js` is located and it's at: `./webportals/node_modules/typescript/lib/typescript.js` But I believe that node_modules is excluded in the default config, anything I'm doing wrong?

**Comment by zeljkoobrenovic** [comment]
That explains it. Add the following in the ignore section of _sokrates/config.json:
`    "ignore": [
        {
            "pathPattern": ".*/node_modules/.*",
            "contentPattern": "",
            "include": true,
            "note": ""
        }
    ],
`

I will take a look and test why this was not done during the init command. The Sokrates init command should have added this include statement. Thanks for spotting this issue.

**Comment by robinvanb** [comment]
This seems to fix it, but the duplication check is taking forever, is this normal behaviour? I've stopped it after 2 hours.
Turns out it's actually 593.177 LOC
